version: "3.8"
services:
  mongodb:
    build: ./database
    container_name: mongodb_c
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    restart: always
  backend:
    build: ./backend
    container_name: backend_c
    environment:
      DATABASE_URL: "mongodb://mongodb_c:27017/hrnetDB"
      PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    command: /bin/sh -c "while ! nc -z mongodb_c 27017; do sleep 1; done; npm run dev:server"
  frontend:
    build: ./frontend
    container_name: frontend_c
    environment:
      VITE_PORT: ${VITE_PORT}
      VITE_PREVIEW_PORT: ${VITE_PREVIEW_PORT}
      VITE_API_URL: ${VITE_API_URL}
      RUN_MODE: ${RUN_MODE}
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
      - "${VITE_PREVIEW_PORT}:${VITE_PREVIEW_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
