name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: devcluster    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.
  IMAGE_BACKEND: backend
  IMAGE_FRONTEND: frontend
  MONGODB_URL: "mongodb://mongodb_c:27017/hrnetDB"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build and push the backend Docker image
      - name: Build and push backend image
        env:
          IMAGE_NAME: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_BACKEND }}
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./backend
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME

      # Build and push the frontend Docker image
      - name: Build and push frontend image
        env:
          IMAGE_NAME: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_FRONTEND }}
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./frontend
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME

      # Deploy the backend and frontend services to the GKE cluster
      - name: Deploy
        env:
          BACKEND_NAME: backend
          FRONTEND_NAME: frontend
        run: |-
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/mongodb-deployment.yaml
          kubectl rollout status deployment/${BACKEND_NAME}
          kubectl rollout status deployment/${FRONTEND_NAME}
