apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/$PROJECT_ID/hrnet-backend:$GITHUB_SHA
          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb-service:27017/hrnetDB"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-persistent-storage
              mountPath: /app
      volumes:
        - name: backend-persistent-storage
          persistentVolumeClaim:
            claimName: backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: 3000
      targetPort: 3000
  type: LoadBalancer
