apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/$PROJECT_ID/hrnet-frontend:$GITHUB_SHA
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-persistent-storage
              mountPath: /app
      volumes:
        - name: frontend-persistent-storage
          persistentVolumeClaim:
            claimName: frontend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 5173
      targetPort: 5173
  type: LoadBalancer
